/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Funcionario;

/**
 *
 * @author info206
 */
public class FuncionarioInt2 extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioInt2
     */
    public FuncionarioInt2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clienteCad = new javax.swing.JButton();
        vendaCad = new javax.swing.JButton();
        filmagemCad = new javax.swing.JButton();
        agendaCad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        clienteCon = new javax.swing.JButton();
        vendaCon = new javax.swing.JButton();
        filmagemCon = new javax.swing.JButton();
        agendaCon = new javax.swing.JButton();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ESCOLHA AS OPÇÕES:");

        jLabel2.setText("CADASTRAR:");

        clienteCad.setText("Cliente");
        clienteCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCadActionPerformed(evt);
            }
        });

        vendaCad.setText("Venda");
        vendaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaCadActionPerformed(evt);
            }
        });

        filmagemCad.setText("Filmagem");
        filmagemCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmagemCadActionPerformed(evt);
            }
        });

        agendaCad.setText("Agenda");
        agendaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaCadActionPerformed(evt);
            }
        });

        jLabel3.setText("CONSULTAR:");

        clienteCon.setText("Cliente");
        clienteCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteConActionPerformed(evt);
            }
        });

        vendaCon.setText("Venda");
        vendaCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaConActionPerformed(evt);
            }
        });

        filmagemCon.setText("Filmagem");
        filmagemCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmagemConActionPerformed(evt);
            }
        });

        agendaCon.setText("Agenda");
        agendaCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaConActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clienteCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(vendaCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filmagemCad, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(agendaCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vendaCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clienteCon, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(filmagemCon, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(agendaCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sair)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteCad)
                    .addComponent(clienteCon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendaCad)
                    .addComponent(vendaCon))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmagemCon)
                    .addComponent(filmagemCad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agendaCon)
                    .addComponent(agendaCad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCadActionPerformed
       new ClienteCad().setVisible(true);
    }//GEN-LAST:event_clienteCadActionPerformed

    private void clienteConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteConActionPerformed
        new ClienteAlt().setVisible(true);
    }//GEN-LAST:event_clienteConActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void vendaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaCadActionPerformed
        new VendaInt().setVisible(true);
    }//GEN-LAST:event_vendaCadActionPerformed

    private void vendaConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaConActionPerformed
        new Vendacon().setVisible(true);
    }//GEN-LAST:event_vendaConActionPerformed

    private void filmagemCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmagemCadActionPerformed
       new  FilmagemCad().setVisible(true);
    }//GEN-LAST:event_filmagemCadActionPerformed

    private void filmagemConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmagemConActionPerformed
        // TODO add your handling code here:
        new  FilmagemCon().setVisible(true);
    }//GEN-LAST:event_filmagemConActionPerformed

    private void agendaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaCadActionPerformed
        new AgendaCad().setVisible(true);
    }//GEN-LAST:event_agendaCadActionPerformed

    private void agendaConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaConActionPerformed
        new AgendaCon().setVisible(true);
    }//GEN-LAST:event_agendaConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioInt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioInt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioInt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioInt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioInt2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendaCad;
    private javax.swing.JButton agendaCon;
    private javax.swing.JButton clienteCad;
    private javax.swing.JButton clienteCon;
    private javax.swing.JButton filmagemCad;
    private javax.swing.JButton filmagemCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton sair;
    private javax.swing.JButton vendaCad;
    private javax.swing.JButton vendaCon;
    // End of variables declaration//GEN-END:variables
}
